### ISSUE TITLE
报错：500Internal Server Error

### ISSUE THREAD

**Issue by mrshawco** [jetplugins/apidocx#56]
![image](https://user-images.githubusercontent.com/89507844/213394316-049323cd-ad2c-426b-ac01-64efd7b2bfab.png)
![image](https://user-images.githubusercontent.com/89507844/213394377-316f24d4-4316-4e59-af0e-f24b5d7e5097.png)
请问下为什么报错了
![image](https://user-images.githubusercontent.com/89507844/213394608-49d8b168-68c8-4eee-a364-fdf94d3d64d0.png)
下面这种就没有报错

**Comment by lkqm** [comment]
年后我看下

**Comment by lkqm** [comment]
麻烦把R、LoginParam类代码发下
