### ISSUE TITLE
feat: 支持接入 Postcat

### ISSUE THREAD

**Issue by scarqin** [jetplugins/apidocx#59]
https://github.com/Postcatlab/postcat/issues/227

**Comment by lkqm** [comment]
了解了下postcat功能很有意思，应该处于发展初期，使用人数没那么普及。目前较忙暂时不会考虑接入postcat，如果有人贡献代码欢迎PR，同时也很乐意提供相关的开发帮助。

**Comment by scarqin** [comment]
@lkqm 谢谢～

**Comment by lkqm** [comment]
目前的转换工作在插件中做的，接入一个新平台主要做的工作：
