### ISSUE TITLE
用idea打开项目代码没有智能提示是为什么

### ISSUE THREAD

**Issue by aholeye** [jetplugins/apidocx#67]

**Comment by aholeye** [comment]
就是apidocx这个项目的代码

**Comment by lkqm** [comment]
有两种可能：1.gradle idea相关依赖未自动下载（网络原因可能要翻墙），2.使用了idea社区版（社区版对插件使用gradle开发有问题）

**Comment by aholeye** [comment]
谢谢我检查下，另外我发现用idea打开这个项目就会使idea工作不正常，比如说右键无法弹出菜单，还有高cpu占用。
不清楚原因，我只能用vscode写，再回到idea debug。调试完及时关闭项目

**Comment by lkqm** [comment]
我也是遇到的，用旗舰版本就没有问题

**Comment by aholeye** [comment]
IntelliJ IDEA 2023.1.2 (Ultimate Edition)
Build #IU-231.9011.34, built on May 16, 2023
Licensed to Spike Yee
Subscription is active until February 23, 2024.
Runtime version: 17.0.6+10-b829.9 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2
GC: G1 Young Generation, G1 Old Generation
Memory: 10000M
Cores: 10
Metal Rendering is ON
Registry:
    debugger.watches.in.variables=false
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.github.copilot (1.2.8.2631)
    net.ashald.envfile (3.4.1)
    yapix (1.1.2)
    MavenRunHelper (4.23.222.2964.0)
    zielu.gittoolbox (500.0.9+213)

Kotlin: 231-1.8.21-IJ9011.34
我怀疑我可能版本太新了 又是启用了new UI
