### ISSUE TITLE
最新版1.1.3怎么没有本地安装包呢

### ISSUE THREAD

**Issue by dikas2017** [jetplugins/apidocx#70]
我看1.1.3修复了getter大量提示的问题，这个挺重要的，1.1.2因为这个问题现在用着都挺卡，我都暂时转用其它插件了。但还是觉得不如apidocx好用，看到终于修复了打算重新用回来，结果怎么没有本地安装包呢，IDEA插件市场也没更新到1.1.3的，请问要怎么更新

**Comment by lkqm** [comment]
v1.1.3版本由于插件审核要求处理兼容性问题，最近忙没暂时没处理，目前需要手动安装插件，下载地址: [v1.1.3](https://github.com/jetplugins/apidocx/releases/tag/v1.1.3)

**Comment by dikas2017** [comment]
> v1.1.3版本由于插件审核要求处理兼容性问题，最近忙没暂时没处理，目前需要手动安装插件，下载地址: [v1.1.3](https://github.com/jetplugins/apidocx/releases/tag/v1.1.3)

好的，十分感谢

**Comment by lkqm** [comment]
v1.1.3版本插件中心可下载了
