### ISSUE TITLE
idea2022.3.3 使用rap2上传卡死

### ISSUE THREAD

**Issue by xulang** [jetplugins/apidocx#71]
idea2022.3.3 使用rap2上传卡死

**Comment by lkqm** [comment]
能详细描述一下吗，插件版本，是IDEA卡死不能动，还是上传失败?，之前的旧版本会卡死吗？另外如果使用生成markdown是否会卡死

**Comment by xulang** [comment]
插件是现在市场里的最新的，具体版本号忘记了，就是界面卡主了，只能通过任务管理器结束它，markdown没试过


---原始邮件---
发件人: &quot;Mario ***@***.***&gt;
发送时间: 2023年8月25日(周五) 下午5:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jetplugins/apidocx] idea2022.3.3 使用rap2上传卡死 (Issue #71)




 
能详细描述一下吗，插件版本，是IDEA卡死不能动，还是上传失败?，之前的旧版本会卡死吗？另外如果使用生成markdown是否会卡死
 
&mdash;

**Comment by lkqm** [comment]
选择单个方法试试，我怀疑有两种可能：1.解析的部分接口代码存在bug, 2.还有就是网络不同，可以尝试从这两个方向上提供更多信息。如果单个方法没问题，那很可能是1问题，可以安装下1.1.3版本（离线安装，或者等几天插件商店更新后）

**Comment by xulang** [comment]
好的


---原始邮件---
发件人: &quot;Mario ***@***.***&gt;
发送时间: 2023年8月25日(周五) 晚上6:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jetplugins/apidocx] idea2022.3.3 使用rap2上传卡死 (Issue #71)




 
选择单个方法试试，我怀疑有两种可能：1.解析的部分接口代码存在bug, 2.还有就是网络不同，可以尝试从这两个方向上提供更多信息。如果单个方法没问题，那很可能是1问题，可以安装下1.1.3版本（离线安装，或者等几天插件商店更新后）
 
&mdash;

**Comment by lkqm** [comment]
v1.1.3版本插件可下载了，你看下还有问题吗

**Comment by xulang** [comment]
我刚升级到了1.1.3 上传api的时候还是会卡主IDE

**Comment by lkqm** [comment]
需要提供下卡住的示例代码

**Comment by xulang** [comment]
代码是公司的代码，不好提供，我用 2021.3.3 社区版同样的代码没啥问题，我现在就是需要上传api的时候在社区版上传

**Comment by lkqm** [comment]
那有点难排查，你可以尝试写一些demo代码，看下能否复现
