### ISSUE TITLE
建议备注中枚举显示枚举的值而不是枚举的名称

### ISSUE THREAD

**Issue by lins3000** [jetplugins/apidocx#74]
建议备注中枚举显示枚举的值而不是枚举的名称：
例如枚举：
public enum AreaTypeEnum {

    /**
     * 国家
     */
    COUNTRY(1),

    /**
     * 省份、直辖市
     */
    PROVINCE(2),

    /**
     * 地市
     */
    CITY(3),

    /**
     * 区县
     */
    AREA(4);

    private final Integer type;
}
文档中备注应该显示枚举的值：1:国家,2:省份、直辖市,3:地市,4:区县
而不是枚举的名称：COUNTRY:国家,PROVINCE:省份、直辖市,CITY:地市,AREA:区县

**Comment by lkqm** [comment]
下一个版本支持下这种情况，实现方式会使用文档注释指定，例如：
```
/**
 * 状态
 * @see com.simples.constant.AreaTypeEnum#type
 */
private AreaTypeEnum areaType;
```
