### ISSUE TITLE
yapi 上传问题

### ISSUE THREAD

**Issue by 0scarecrow0** [jetplugins/apidocx#75]
两个接口的@Apioperation 一样，但是path 不一致，上传至yapi ，只会生成一个接口，后上传的接口会覆盖第一个。上传规则是什么如何判断是新增还是更新

**Comment by 0scarecrow0** [comment]
上传 yapi 的匹配规则是什么

**Comment by lkqm** [comment]
会按照这个优先级关系进行接口匹配：title+path+method > title + path > title ， 以满足一个API这3个部分中信息变更.
