### ISSUE TITLE
您好，请问我们copy markdown可以一起生成一个返回示例吗

### ISSUE THREAD

**Issue by XXXIERW** [jetplugins/apidocx#81]
![image](https://github.com/jetplugins/apidocx/assets/42667466/176103b6-cda6-4aca-8cb7-1603afb538a1)
参考easydoc

感谢您的分享！

**Comment by XXXIERW** [comment]
EasyApi

**Comment by lkqm** [comment]
可以这么做，比如根据文档规则生成一些类型、枚举，但是这里有个问题，生成得示例数据，并不一定是期望得，还是说我只是想要这个json内容？

**Comment by XXXIERW** [comment]
对的，大佬，其实只是想要json内容，因为在实际应用中，如果生成的返回参数比较复杂前端可能看不懂说参数结构是怎么样的，所以有这个json内容 可以减少一定量的沟通～

**Comment by XXXIERW** [comment]
目前使用也发现如果是Long类型的话在文档里面导出来对应的类型会变成Integer 这个也可以看下～

**Comment by lkqm** [comment]
> 目前使用也发现如果是Long类型的话在文档里面导出来对应的类型会变成Integer 这个也可以看下～

openapi规范来说没有long, integer都是 integer类型

**Comment by lkqm** [comment]
已经添加，后续添加其他需求，再发一个版本

**Comment by lkqm** [comment]
插件商店已发版，大概2天左右可以收到更新
