### ISSUE TITLE
你好，上传showdoc的时候一直提示验证码错误

### ISSUE THREAD

**Issue by Thepatterraining** [jetplugins/apidocx#82]
输错了提示验证码还不换，输对了还提示，并且换了个验证码。

**Comment by lkqm** [comment]
目前使用账号密码方式登录，服务端接口有变化，需要插件重新适配下

**Comment by Thepatterraining** [comment]
好的，什么时候能适配好呢，到时候我更新一下插件就好了吗

**Comment by lkqm** [comment]
前面回复有错误，接口确实变化了但是老接口是保留的，但是刚刚我试了一下，是可以登录上传的，请确认下，是否是用的：https://www.showdoc.com.cn ，然后再试试

**Comment by lkqm** [comment]
验证码提示错误，有可能是账号密码不正确

**Comment by Thepatterraining** [comment]
不是用的这个地址，是我们本地部署的showdoc，跟这个有关系吗，账号密码是正确的。

**Comment by Thepatterraining** [comment]
抱歉，我看错了，配置里面的本地showdoc地址又变成https://www.showdoc.com.cn/了，我修改以后好使了，感谢

**Comment by lkqm** [comment]
好的 没问题
