### ISSUE TITLE
controller @RequestMapping 多个路径只能识别一个

### ISSUE THREAD

**Issue by chelseXie** [jetplugins/apidocx#85]
@RestController
@RequestMapping({CoreConstants.OUTER_INTEFACE_URL_PREFIX + "/adviser",CoreConstants.OUTER_INTEFACE_URL_PREFIX + "/hha"})
类似这种，目前导出openapi只导出了前面那个路径的接口

**Comment by lkqm** [comment]
设计是这样的，同一个方法使用了同一个接口标题，上传到API文档管理平台，会根据标题进行更新相同接口，所以只设计支持读取了第一个路径，暂时没有想到更好的办法处理这种情况

**Comment by lkqm** [comment]
看了下导出openapi文档是支持的
