### ISSUE TITLE
ShowDoc 有打算继续更新吗？可调试接口能生成文档吗？修改方便点

### ISSUE THREAD

**Issue by mr-dragon** [jetplugins/apidocx#87]
如题：ShowDoc能生成 **可调试接口** 文档吗？

<img width="229" alt="2024-06-27 20 02 25@2x" src="https://github.com/jetplugins/apidocx/assets/25114117/dacf9f6c-5687-4ca0-9c8a-17a593cd1171">

- https://www.showdoc.com.cn/runapi/30291
- [自动生成API文档](https://www.showdoc.com.cn/page/741656402509783)

![自动生成runapi文档](https://github.com/jetplugins/apidocx/assets/25114117/2a82d1af-e70b-4eb6-b0ac-cc9b3b047e39)

**Comment by lkqm** [comment]
暂时不打算接入runapi, 如果感兴趣可以pr增加该功能
