### ISSUE TITLE
【required】注解在yapi不生效

### ISSUE THREAD

**Issue by excel-bat** [jetplugins/apidocx#90]
<img width="850" alt="image" src="https://github.com/user-attachments/assets/93766827-f542-420e-9fac-fe16216e8b76">
看代码目前只支持validate 注解，swagger 的@ApiModelProperty(value = "手机号", required = true) required不生效

**Comment by lkqm** [comment]
是的  参数校验时候必传字段一般都会使用注解校验

**Comment by excel-bat** [comment]
@ApiModelProperty 的 required=true 字段，这个可以支持么

**Comment by lkqm** [comment]
请问下是什么情况下需要了，swagger不支持@NotNull之类注解吗？
